services:
  - type: web
    name: whisperer-gpt
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        value: sk-XXXX-YOUR-REAL-KEY

